# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b816984b5558c8396028497ddb68aa1bd38990f693ade38e59e951721904442f316ee45658bfa882009f8c0cd6c2bf5b35663e851196b6b8e2ec007156152f3b

test:
  secret_key_base: bf2bad48c60647d18fd3c8821254c313ad40a6313f373772e5cda872a1c4a68508b9c642896c270ce54cd6375b827deb68dca56ced8461372ead3589f46ba153

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
